config/routes.rb
FileManager::Application::routes.draw do
  resources :user_sessions
  resources :documents
  resources :client_comments
  resources :document_statuses, :client_statuses, :base_folders

  resources :users do
    get :change_status,          :on => :member
    get :set_current_staff_user, :on => :member
  end

  resources :clients do
    get :set_current_client, :on => :member
  end

  resources :folders do
    get :set_current_folder, :on => :member
    get :nest,               :on => :member
    put :populate,           :on => :collection
  end

  resources :documents do
    get :download_document, :on => :member
  end

  resources :client_perms do
    put :assign,                        :on => :collection
    get :set_current_staff_user_client, :on => :member
    get :delete_perms,                  :on => :member
  end

  resources :folder_perms do
    put :assign, :on => :collection
  end

  match '/login',                   :to => 'user_sessions#new'
  match '/logout',                   :to => 'user_sessions#destroy'
  match '/reset',                    :to => 'user_sessions#reset'
  match '/change',                   :to => 'users#edit_password'
  match '/update_password',          :to => 'users#update_password'
  match '/help',                     :to => 'users#toggle_help'
  match '/set_theme',                :to => 'users#set_theme'
  match 'admin',                     :to => 'admin#instruct'
  match 'basic_info',                :to => 'clients#edit'
  match 'notes',                     :to => 'client_comments#index'
  match 'display_privacy_statement', :to => 'welcome#display_privacy_statement'
  root                               :to => 'welcome#index'

end

app/models/user.rb
require 'digest/sha1'
class User < ActiveRecord::Base

  acts_as_authentic

  has_many :comments, :as => :commentable, :order => "created_at DESC"
  has_many :client_perms
  has_many :folder_perms
  has_many :client_comments
  belongs_to :role
  belongs_to :client        # this is for an external client which can have many users

  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :display_name, :email, :password, :password_confirmation,
                  :comment, :active, :role_id, :client_id
  attr_reader :password

  validates_presence_of :display_name, :role_id

  validate                  :correct_client_assignment

  private

  def correct_client_assignment
    role = Role.find_by_name('eclient')
    if client_id.blank? && role_id == role.id
      errors.add :client_id, "must assign an external client to this user"
    elsif !client_id.blank? && role_id != role.id
      errors.add :client_id, "cannot assign an internal user to a client"
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :login_required
  #ssl_required  :new, :create, :edit, :update, :edit_password, :update_password

  def index
    @role_array = Role.all.collect {|r| [r.name,r.id.to_s]}
    @search_fields_array = ["email","username"]
    #@users = User.search(params[:search], params[:page], get_search_field)
    if (params[:which_action].nil?) || (params[:which_action] == "Search")
      @users = User.my_search(params[:search], params[:page], get_search_field,"not_staff",[])
    else                # params[:which_action] == "Filter"
      @users = User.filter_by_status(params[:filter_by], params[:page], "role_id","not_staff",[])
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, :notice => "User account created and is ready for use."
    else
      render :action => 'new'
    end
  end

  def edit
    # only admins are going to access this under current assumptions
    @user = User.find(params[:id])
  end

  def edit_password
    @user = @current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = 'User data was successfully updated.'
      redirect_to(is_internal? ? users_path : edit_user_path(@user))
    else
      render :action => "edit"
    end
  end

  def update_password
    @user = @current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Password successfully updated."
      redirect_to(is_internal? ? clients_path : edit_client_path(current_user.client))
    else
      flash.now[:error] = current_user.errors[:base] || "There was a problem updating your password."
      render :action => :edit
    end
  end

  def set_current_staff_user
    @current_staff_user = User.find(params[:id])
    session[:staff_user_id] = @current_staff_user.id
    flash[:notice] = "Current staff user set to #{current_staff_user.display_name}. Assign client permissions."
    redirect_to :controller => 'client_perms', :action => 'index'
  end

  def change_status
    @user = User.find(params[:id])
    @user.update_attribute(:active, (@user.active ? false : true))
    flash[:warning] = "Set user status to " + (@user.active ? "active" : "in-active") + " for " + @user.username
    redirect_to users_path
  end

  def set_theme
    current_user.update_attribute(:theme, params[:id])
    redirect_to :back, :notice => "Set the new theme to #{params[:id]}"
  end

  def toggle_help
    current_user.update_attribute(:help_on, !current_user.help_on)
    redirect_to :back, :notice => "System wide help has been turned " + (current_user.help_on ? "on" : "off")
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= labeled_form_for @user, :html => {:class => 'form'} do |f|
  = f.error_message_on :base
  .columns
    .column.left
      = f.text_field :username
      = f.text_field :display_name
      = f.text_field :email, :label => "Email Address"
      = f.password_field :password
      = f.password_field :password_confirmation, :label => "Confirm Password"
      - if is_admin?
        = f.submit 'Submit', :cancel => {:action => 'index'}
    .column.right
      = f.check_box :active
      = f.collection_select :role_id, Role.all, :id, :display_name
      = f.collection_select :client_id, Client.all, :id, :client_name, {:include_blank => true}
      = f.text_area :comment, :rows => 7, :cols => 50
    .clear

app/views/users/edit.html.haml
%h3
  = h_link_to("Edit User","../../help/user_edit")
= render :partial => 'form'

app/views/users/edit_password.html.haml
%h3
  = h_link_to('Change Password', "help/change_password")
= form_for @user, :url => update_password_path do |f|
  %p
    %strong
      = f.label :password, "New Password"
    %br/
    = f.password_field :password
  %p
    %strong
      = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  = f.submit 'Change Password'

app/views/users/index.html.haml
= render_crud_table(@users,'users',['id','username','email','active'],@search_fields_array, @role_array,'user_actions')

app/views/users/new.html.haml
%h3
  = h_link_to('Create User', "../../help/user_new")
= render :partial => 'form'