config/routes.rb
FileManager::Application::routes.draw do
  resources :user_sessions
  resources :documents
  resources :client_comments
  resources :document_statuses, :client_statuses, :base_folders

  resources :users do
    get :change_status,          :on => :member
    get :set_current_staff_user, :on => :member
  end

  resources :clients do
    get :set_current_client, :on => :member
  end

  resources :folders do
    get :set_current_folder, :on => :member
    get :nest,               :on => :member
    put :populate,           :on => :collection
  end

  resources :documents do
    get :download_document, :on => :member
  end

  resources :client_perms do
    put :assign,                        :on => :collection
    get :set_current_staff_user_client, :on => :member
    get :delete_perms,                  :on => :member
  end

  resources :folder_perms do
    put :assign, :on => :collection
  end

  match '/login',                   :to => 'user_sessions#new'
  match '/logout',                   :to => 'user_sessions#destroy'
  match '/reset',                    :to => 'user_sessions#reset'
  match '/change',                   :to => 'users#edit_password'
  match '/update_password',          :to => 'users#update_password'
  match '/help',                     :to => 'users#toggle_help'
  match '/set_theme',                :to => 'users#set_theme'
  match 'admin',                     :to => 'admin#instruct'
  match 'basic_info',                :to => 'clients#edit'
  match 'notes',                     :to => 'client_comments#index'
  match 'display_privacy_statement', :to => 'welcome#display_privacy_statement'
  root                               :to => 'welcome#index'

end

app/models/client_comment.rb
class ClientComment < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
  attr_accessible :content, :client_id, :user_id
  validates_presence_of :content, :message => "^Empty comment/notes cannot be saved."  

  # define_index do
  #   indexes content
  #   has client_id, created_at
  #   set_property :delta => true
  # end

end

app/controllers/client_comments_controller.rb
class ClientCommentsController < ApplicationController

  before_filter :current_client_selection_required
  before_filter :set_notes_tab

  def index
    @comments  = current_client.client_comments.search(params[:search] || "",
                                                           :page => params[:page] || 1, :per_page => 10,
                                                           :order => :created_at, :sort_mode => :desc,
                                                           :match_mode => :boolean)
    @client = current_client
  end

  def create
    @comment = ClientComment.create!(params[:client_comment])
    unless params[:send_email].nil?
      # wants to send the email
      commenting_user_id = @comment.user_id
      @client_user = @comment.client.user
      email_subject = params[:subject]
      email_text    = @comment.content
      send_email(@client_user, commenting_user_id, email_subject, email_text)
    end
    redirect_to :controller => 'client_comments', :action => 'index'
  end

  protected

  def set_notes_tab
    #self.class.current_tab :notes
  end

end

app/helpers/client_comments_helper.rb
module ClientCommentsHelper
end

app/views/client_comments/_new_client_comment.html.haml
- help_screen = ((is_internal?) ? 'notes_to_user' : 'notes_to_admin')
%h3
  = h_link_to('Add a Note or Comment',"help/#{help_screen}")
= form_for ClientComment.new(:client => new_client_comment) do |f|
  = f.hidden_field :client_id, :value => current_client.id
  = f.hidden_field :user_id, :value => current_user.id
  %p
    = f.label :content, "Notes or Comments:"
    %br
    = f.text_area :content, :rows => 8, :cols => 80
  %p
    = check_box_tag :send_email
    = label_tag :send_email, "Send Email?"
  %p
    = label_tag :subject, "Subject:"
    %br
    = text_field_tag :subject, '', :size => 80, :disabled => true
  %p
    = f.submit "Submit"

:javascript

  $(function() {
    $('#send_email').click(function() {
      $('#subject').toggleOpposite(!this.checked)
    });
  });

app/views/client_comments/index.html.haml
- header_string = "Comments for " + show_current_client + " - most recent first."
%h3
  = h_link_to(header_string, "help/notes")
= form_tag client_comments_path, :method => :get do
  %p
    = text_field_tag :search, params[:search]
    = submit_tag "Search", :name => nil
#accordion
  - for comment in @comments
    %h5
      %a{ :href => "#" }
        = (comment.user.display_name + " on " + comment.created_at.strftime('%A, %m/%d/%Y, at %I:%M%p') + ".  " + comment.content[0, 60]) + " ...."
    %ul{ :style => "list-style-type: none" }
      %li
        = simple_format(comment.content)
        .clear
.actions-bar
  .pagination
    = will_paginate @comments
  .clear
- if @client
  = render :partial => 'new_client_comment', :object => @client